### ISSUE TITLE
Failure on imports of SUSE Studio exports

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/obs-service-kiwi_import#14]
I got a failure when trying to import a kiwi configuration from Studio. The tarball and error message can be found here:

https://build.opensuse.org/package/show/home:bgeuken:images/suse_studio_image

```
Files could not be expanded: service error: from /usr/lib/obs/service//kiwi_import:40:in `'

service kiwi_import failed: 
Use of uninitialized value $val in concatenation (.) or string at /usr/lib/obs/server/bs_admin line 1144. 
/srv/obs/service/10934 
/srv/obs/service/10934/src 
/srv/obs/service/10934/src/_service 
/srv/obs/service/10934/src/source.kiwi.txz 
/srv/obs/service/10934/src/.old 
/srv/obs/service/10934/out 
/srv/obs/service/10934/var 
/srv/obs/service/10934/var/cache 
/srv/obs/service/10934/var/cache/obs 
/srv/obs/service/10934/var/cache/obs/NCFLjyaz8MAy 
/srv/obs/service/10934/var/cache/obs/NCFLjyaz8MAy/scripts 
/srv/obs/service/10934/var/cache/obs/NCFLjyaz8MAy/scripts/inner.sh 
/srv/obs/service/10934/var/cache/obs/NCFLjyaz8MAy/scripts/inner.sh.command 
/srv/obs/service/10934/home 
Running /usr/lib/obs/service//kiwi_import --outdir /var/cache/obs/NCFLjyaz8MAy/out 
+ echo Running /usr/lib/obs/service//kiwi_import --outdir /var/cache/obs/NCFLjyaz8MAy/out 
+ export HOME=/var/cache/obs/NCFLjyaz8MAy/home 
+ HOME=/var/cache/obs/NCFLjyaz8MAy/home 
+ /usr/lib/obs/service//kiwi_import --outdir /var/cache/obs/NCFLjyaz8MAy/out 
/usr/lib/obs/service/KiwiImport/lib/repository_replacer.rb:18:in `replace_sle_placeholder!': undefined method `each' for nil:NilClass (NoMethodError) 
from /usr/lib/obs/service/KiwiImport/lib/repository_replacer.rb:10:in `replace!' 
from /usr/lib/obs/service//kiwi_import:40:in `'
```

**Comment by ChrisBr** [comment]
@bgeuken Problem seems to be SLES, with openSUSE it works, just tried:
https://build.opensuse.org/package/view_file/home:cbruckmayer/fooosdafsdafasdf/config.kiwi?expand=1
